import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import datetime

# Set styling for plots
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# ==========================================
# STEP 1: DATA GENERATION & CLEANING
# ==========================================
print("--- Step 1: Generating and Cleaning Data ---")

# Creating a realistic retail dataset (Daily sales over 2 years)
np.random.seed(42)
dates = pd.date_range(start="2024-01-01", end="2025-12-31", freq="D")
n_days = len(dates)

categories = ['Electronics', 'Clothing', 'Home & Kitchen', 'Beauty']
category_choices = np.random.choice(categories, size=n_days)

# Generate base sales with a growth trend and weekend spikes
base_sales = np.linspace(1000, 2500, n_days)
weekend_booster = np.array([500 if d.weekday() >= 5 else 0 for d in dates])
noise = np.random.normal(0, 150, n_days)
sales_amount = base_sales + weekend_booster + noise

df = pd.DataFrame({
    'Date': dates,
    'Category': category_choices,
    'Sales': sales_amount,
    'Transactions': np.random.randint(10, 50, size=n_days)
})

# Introduce a few missing values to demonstrate data cleaning
df.loc[df.sample(frac=0.02).index, 'Sales'] = np.nan

# Handle missing values by filling them with the median sales of that category
df['Sales'] = df.groupby('Category')['Sales'].transform(lambda x: x.fillna(x.median()))

print(df.head(), "\n")

# ==========================================
# STEP 2: EXPLORATORY DATA ANALYSIS (EDA)
# ==========================================
print("--- Step 2: Running Exploratory Data Analysis ---")

# Extract time features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['DayOfWeek'] = df['Date'].dt.dayofweek # 5=Sat, 6=Sun

# Aggregate total sales by category
category_sales = df.groupby('Category')['Sales'].sum().reset_index()

# Visualization 1: Sales Distribution by Category
plt.figure()
sns.barplot(data=category_sales, x='Category', y='Sales', palette='Blues_d')
plt.title('Total Revenue Generated by Category (2024 - 2025)')
plt.ylabel('Total Sales ($)')
plt.xlabel('Product Category')
plt.tight_layout()
plt.show()

# Visualization 2: Monthly Sales Trends over Time
monthly_sales = df.groupby(['Year', 'Month'])['Sales'].sum().reset_index()
monthly_sales['DateString'] = monthly_sales['Year'].astype(str) + '-' + monthly_sales['Month'].astype(str).str.zfill(2)

plt.figure()
sns.lineplot(data=monthly_sales, x='DateString', y='Sales', marker='o', color='crimson')
plt.xticks(rotation=45)
plt.title('Monthly Storewide Sales Performance')
plt.ylabel('Total Sales ($)')
plt.xlabel('Timeline (YYYY-MM)')
plt.tight_layout()
plt.show()

# ==========================================
# STEP 3: FEATURE ENGINEERING & PREDICTION
# ==========================================
print("--- Step 3: Training the Prediction Model ---")

# We want to predict daily 'Sales' based on historical indicators:
# - Day of the week
# - Numerical index representing time progression (Trend)
# - Number of Transactions
df['TimeIndex'] = np.arange(len(df))

X = df[['TimeIndex', 'DayOfWeek', 'Transactions']]
y = df['Sales']

# Split into 80% Training and 20% Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate Evaluation Metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Model Evaluation Metrics:")
print(f"-> Root Mean Squared Error (RMSE): ${rmse:.2f}")
print(f"-> R-squared Score: {r2:.4f} (Explains {r2*100:.1f}% of data variance)\n")

# ==========================================
# STEP 4: PRESENT FINDINGS
# ==========================================
print("--- Step 4: Visualizing Predictions ---")

# Visualization 3: Actual vs Predicted Sales Comparison
plt.figure()
plt.scatter(y_test, y_pred, alpha=0.6, color='purple')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2)
plt.xlabel('Actual Sales ($)')
plt.ylabel('Predicted Sales ($)')
plt.title('Prediction Validation: Actual vs Predicted Daily Sales')
plt.tight_layout()
plt.show()

print("Project run successfully! Review the charts displayed to build your final report slides.")